[package]
name = "libwebcamrs"
version = "0.1.0"
authors = ["Junichi Kajiwara <junichi.kajiwara@gmail.com>"]

[lib]
name="webcamrs"
crate-type = ["dylib"]

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }

[dependencies]
libc = "0.1"